# Describes the docker-compose configuration for development environments.
# These settings are not secure and are not intended for production use.
# Please override this configuration when configuring a production instance.
# This config launch Flask / Postgres / Redis / Celery

version: '3.2'

services:
  db:
    image: postgres:12.2-alpine
    env_file:
      - ./dockerenv/env.dev
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    ports:
      - 5432:5432

  app:
    build: .
    depends_on:
      - db
    env_file:
      - ./dockerenv/env.dev
    ports:
      - 5000:5000

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  postgres:
