# -*- coding: utf-8 -*-
# File     : docker-compose.yml
# Authors  : Austin Schaffer <schaffer.austin.t@gmail.com
#            Matthieu Petiteau <mpetiteau.pro@gmail.com>
# Date     : 12.01.2020
# Desc     : Describes the docker-compose configuration for development environments.
#            These settings are not secure and are not intended for production use.
#            Please override this configuration when configuring a production instance.
#            This config launch Flask / MySQL / Redis / Celery

version: '3.2'

services:
  db:
    image: mysql/mysql-server:5.7
    env_file:
      - ./dockerenv/env.dev-mysql
    volumes:
      - ./mysql/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:6.0-rc-alpine
    command: redis-server --requirepass redis123
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  app:
    build: .
    command: python -m flask run --host="0.0.0.0" --port="5000"
    depends_on:
      - db
    env_file:
      - ./dockerenv/env.dev-shhh
    ports:
      - 5000:5000

  celeryworker:
    build: .
    command: >
      celery -A shhh.celery.tasks worker
      --loglevel=INFO
      --logfile=/var/log/celery/celeryworker-shhh.log
      --pidfile=/var/run/celery/celeryworker-shhh.pid
    env_file:
      - ./dockerenv/env.dev-shhh

  celerybeat:
    build: .
    command: >
      celery -A shhh.celery.tasks beat
      --loglevel=INFO
      --logfile=/var/log/celery/celerybeat-shhh.log
      --pidfile=/var/run/celery/celerybeat-shhh.pid
      --schedule=/var/run/celery/celerybeat-schedule
    env_file:
      - ./dockerenv/env.dev-shhh

  flower:
    image: mher/flower
    command: flower --broker=redis://:redis123@redis:6379 --port=8888
    ports:
      - 8888:8888

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  mysql_data:
  redis:
